---
rule-providers:
  RP-whatsapp:
    type: file
    behavior: classical
    path: "./rule_provider/whatsapp.yaml"
  RP-bstation:
    type: file
    behavior: classical
    path: "./rule_provider/bstation.yaml"
  RP-portgame:
    type: file
    behavior: classical
    path: "./rule_provider/portgame.yaml"
  RP-speedtest:
    type: file
    behavior: classical
    path: "./rule_provider/speedtest.yaml"
  RP-zoom:
    type: file
    behavior: classical
    path: "./rule_provider/zoom.yaml"
  RP-indo:
    type: file
    behavior: classical
    path: "./rule_provider/indo.yaml"
proxy-providers:
  SERV-SG:
    type: file
    path: "./proxy_provider/akun-SG.yaml"
    health-check:
      enable: true
      url: http://www.gstatic.com/generate_204
      interval: 180
proxy-groups:
- name: SERVER-SG
  type: select
  use:
  - SERV-SG
- name: DIRECT-INDI
  type: select
  interface-name: eth1
  proxies:
  - DIRECT
- name: PG-whatsapp
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-facebook
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-google
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-telegram
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-tiktok
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-twitter
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-bstation
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
- name: PG-speedtest
  type: select
  proxies:
  - SERVER-SG
  - DIRECT-INDI
  url: http://www.gstatic.com/generate_204
  interval: '300'
port: 7890
socks-port: 7891
mixed-port: 7893
redir-port: 7892
tproxy-port: 7895
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
ipv6: false
external-controller: 192.168.10.1:9090
external-ui: "/usr/share/openclash/ui"
secret: '123456'
profile:
  store-selected: true
  store-fake-ip: false
sniffer:
  enable: true
  sniffing:
  - tls
  - http
  ForceDnsMapping: false
  ParsePureIp: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssot.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - "+.jd.com"
  port-whitelist:
  - 443
  - 80
dns:
  enable: true
  listen: 0.0.0.0:7874
  default-nameserver:
  - 1.1.1.1
  - 1.0.0.1
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  nameserver:
  - https://dns.cloudflare.com/dns-query
  fallback:
  - tls://1.1.1.1:853
  fallback-filter:
    geoip: true
    geoip-code: ID
    ipcidr:
    - 0.0.0.0/8
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.0.0.0/24
    - 192.0.2.0/24
    - 192.88.99.0/24
    - 192.168.0.0/16
    - 198.18.0.0/15
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - 240.0.0.0/4
    - 255.255.255.255/32
    domain:
    - "+.google.com"
    - "+.facebook.com"
    - "+.youtube.com"
    - "+.githubusercontent.com"
    - "+.googlevideo.com"
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - msftconnecttest.com
    - msftncsi.com
    - "+.*"
  ipv6: false
rules:
- DST-PORT,7895,REJECT
- DST-PORT,7892,REJECT
- DOMAIN-SUFFIX,ml.youngjoygame.com,DIRECT-INDI
- SRC-IP-CIDR,172.16.21.251/32,SERVER-SG
- SRC-IP-CIDR,172.16.21.11/32,DIRECT-INDI
- SRC-IP-CIDR,172.16.21.12/32,SERVER-SG
- IP-CIDR,198.18.0.1/16,REJECT,no-resolve
- IP-CIDR,103.253.27.84/32,DIRECT-INDI
- IP-CIDR,38.9.141.66/32,DIRECT-INDI
- DOMAIN-SUFFIX,arwnetwork.one,DIRECT-INDI
- GEOIP,private,DIRECT-INDI,no-resolve
- RULE-SET,RP-whatsapp,PG-whatsapp
- RULE-SET,RP-bstation,PG-bstation
- RULE-SET,RP-speedtest,PG-speedtest
- RULE-SET,RP-zoom,DIRECT-INDI
- GEOSITE,facebook,PG-facebook
- GEOIP,facebook,PG-facebook
- GEOSITE,google,PG-google
- GEOIP,google,PG-google
- GEOSITE,twitter,PG-twitter
- GEOIP,twitter,PG-twitter
- GEOSITE,telegram,PG-telegram
- GEOIP,telegram,PG-telegram
- GEOSITE,tiktok,PG-tiktok
- GEOIP,id,DIRECT-INDI
- RULE-SET,RP-indo,DIRECT-INDI
- GEOIP,cloudflare,DIRECT-INDI
- GEOSITE,microsoft,SERVER-SG
- RULE-SET,RP-portgame,DIRECT-INDI
- MATCH,GLOBAL